# Generated by Django 5.0 on 2024-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('gym_id', models.IntegerField()),
                ('diet_plan', models.CharField(max_length=400)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
